[package]
name = "runtime-target-feature"
version = "0.1.0"
authors = ["James Duley <jagduley@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.3"

[dependencies.syn]
version = "0.11"
features = ["full"]

[workspace]
members = ["rt", "tests"]
